### ISSUE TITLE
How to use svg visualizer

### ISSUE THREAD

**Issue by kadinzhang** [tensorflow/magenta-js#281]
I saw that #260 was pushed out to resolve some issues with the canvas visualizer. At the time of me writing this, [docs](https://tensorflow.github.io/magenta-js/music/classes/_core_visualizer_.visualizer.html) haven't been updated - how can I use this mm.PianoRollSVGVisualizer? I tried using the same params as the old Visualizer(), swapping out the canvas element with a generic div, and although it returned no errors, nothing was rendered.

**Comment by notwaldorf** [comment]
Sorry about that! We've updated the [docs](https://tensorflow.github.io/magenta-js/music/classes/_core_visualizer_.pianorollsvgvisualizer.html) -- the parameter to the constructor is an `svg` element, not a `div`. Here's a [usage example](https://github.com/tensorflow/magenta-js/blob/master/music/demos/visualizer.ts#L74).

We should probably throw an error if the tag name of the thing you pass to the constructor isn't `svg`, since that would've sorted out your question. Would you be interested in sending that PR?

**Comment by kadinzhang** [comment]
Sure! That sounds fun. I'll give it a try.

**Comment by notwaldorf** [comment]
This was fixed in https://github.com/tensorflow/magenta-js/pull/291
