### ISSUE TITLE
`run` callback called after `Player.stop()`

### ISSUE THREAD

**Issue by cifkao** [tensorflow/magenta-js#380]
`SoundFontPlayer` sometimes continues the playback for a very short time (invoking the `run` callback) after the `stop` method has been called. This typically happens when there is a rapid sequence of notes.

This can cause problems for example when using the player together with a `Visualizer` and trying to `clear` it or display something else on the same canvas immediately after calling `stop`. In this case, the old `NoteSequence` will overwrite the new content of the canvas.

**Comment by notwaldorf** [comment]
Oh, interesting! I think the fix might be to also check whether the `this.currentPart` is still defined when executing the run callback: https://github.com/tensorflow/magenta-js/blob/master/music/src/core/player.ts#L164

Do you have a midi file that reproes this reliably? Maybe a small code sample or something on Glitch or JSBin that I could run? Since I don't know how to cause this to happen, I don't know how to test that I've fixed it... :/

**Comment by cifkao** [comment]
Here is one such file: [playback_test.mid.zip](https://github.com/tensorflow/magenta-js/files/3795928/playback_test.mid.zip)

**Comment by cifkao** [comment]
> I think the fix might be to also check whether the `this.currentPart` is still defined when executing the run callback

...unless someone decides to call `start` again with a different sequence immediately after calling `stop`.

**Comment by notwaldorf** [comment]
That wouldn’t be any different than how it is today though, is it? Also
sounds a bit unsupported — you should stop a player before you start it
again (we can add stronger words in the docs for this)
